version: "3.0"

services:
    anaconda:
      build: 
        context: .
        args:
          # Proxy
          - HTTP_PROXY=$HTTP_PROXY
          - http_proxy=$http_proxy
          - HTTPS_PROXY=$HTTPS_PROXY
          - https_proxy=$https_proxy
          - FTP_PROXY=$FTP_PROXY
          - ftp_proxy=$ftp_proxy
          - NO_PROXY=$NO_PROXY
          - no_proxy=$no_proxy
          # Jupyter
          - jupyter_pass=$jupyter_pass
          - jupyter_dir=$jupyter_dir
          - jupyter_theme=$jupyter_theme
          - add_ch=$add_ch
          - venv_list=$venv_list
          - venv_module=$venv_module
          - nbextensions=$nbextensions
      container_name: $container_name
      tty: true # make container stay launched
      ports: 
        - $port:8888 # jupyter
      command:
        /bin/bash
      volumes: 
        - $local_dir:$jupyter_dir:rw